version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio1
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - ${HOME}/minio/data:/data
    user: "${UID}:${GID}" # Runs as the current user
    command: server /data --console-address ":9001"
    restart: unless-stopped
